services:
  - type: web
    name: cogito-conversational-repl
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    rootDir: ./conversational-repl
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: cogito-postgres
          property: connectionString
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: RECALL_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: RENDER_EXTERNAL_URL
        value: https://cogito-conversational-repl.onrender.com

databases:
  - name: cogito-postgres
    plan: starter
    region: oregon